on: { workflow_dispatch: {} }

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

env:
  VERSION: 0.1.0
  REGISTRY: ghcr.io
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  RUNNING_ON_PRIMARY_BRANCH: true

jobs:
  build-containers:
    runs-on: "ubuntu-latest"

    permissions:
      contents: read
      packages: write

    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: actions/checkout@v4
        with: { path: customize }

      - name: Download AzerothCore
        uses: actions/checkout@v4
        with: { repository: liyunfan1223/azerothcore-wotlk }

      - name: Download PlayerBots
        uses: actions/checkout@v4
        with:
          repository: liyunfan1223/mod-playerbots
          path: modules/mod-playerbots

      - name: Download Eluna
        uses: actions/checkout@v4
        with:
          repository: azerothcore/mod-eluna
          path: modules/mod-eluna

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build worldserver
        uses: ./customize/.github/actions/build-and-publish
        with:
          component-name: worldserver
          push: ${{ env.RUNNING_ON_PRIMARY_BRANCH }}
          registry: ${{ env.REGISTRY }}
          version: ${{ env.VERSION }}

      - name: build authserver
        uses: ./customize/.github/actions/build-and-publish
        with:
          component-name: authserver
          push: ${{ env.RUNNING_ON_PRIMARY_BRANCH }}
          registry: ${{ env.REGISTRY }}
          version: ${{ env.VERSION }}

      - name: build db-import
        uses: ./customize/.github/actions/build-and-publish
        with:
          component-name: db-import
          push: ${{ env.RUNNING_ON_PRIMARY_BRANCH }}
          registry: ${{ env.REGISTRY }}
          version: ${{ env.VERSION }}

      - name: build client-data
        uses: ./customize/.github/actions/build-and-publish
        with:
          component-name: client-data
          push: ${{ env.RUNNING_ON_PRIMARY_BRANCH }}
          registry: ${{ env.REGISTRY }}
          version: ${{ env.VERSION }}

      - name: build tools
        uses: ./customize/.github/actions/build-and-publish
        with:
          component-name: tools
          push: ${{ env.RUNNING_ON_PRIMARY_BRANCH }}
          registry: ${{ env.REGISTRY }}
          version: ${{ env.VERSION }}
